name: mindmate
description: "MindMate - Your Personal Wellness Companion"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  model_viewer_plus: ^1.10.0
  just_audio: ^0.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/illustrations/
    - assets/audio/
    - assets/audio/breathing/box/
    - assets/audio/meditation/stress_relief/quick_reset/