// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3ZlaxV4rAOroeP-eCILThUt0HF-dS4yM',
    appId: '1:279427655646:ios:7ad235caefd9bc69f3df4f',
    messagingSenderId: '279427655646',
    projectId: 'mindmate-app-fcf2d',
    storageBucket: 'mindmate-app-fcf2d.firebasestorage.app',
    iosBundleId: 'com.example.mindmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJi6o3LTZOTT7ZgYuGkt9bgV0-nXQMljM',
    appId: '1:279427655646:web:72328c7ed1125308f3df4f',
    messagingSenderId: '279427655646',
    projectId: 'mindmate-app-fcf2d',
    authDomain: 'mindmate-app-fcf2d.firebaseapp.com',
    storageBucket: 'mindmate-app-fcf2d.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJi6o3LTZOTT7ZgYuGkt9bgV0-nXQMljM',
    appId: '1:279427655646:web:72328c7ed1125308f3df4f',
    messagingSenderId: '279427655646',
    projectId: 'mindmate-app-fcf2d',
    authDomain: 'mindmate-app-fcf2d.firebaseapp.com',
    storageBucket: 'mindmate-app-fcf2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3ZlaxV4rAOroeP-eCILThUt0HF-dS4yM',
    appId: '1:279427655646:ios:7ad235caefd9bc69f3df4f',
    messagingSenderId: '279427655646',
    projectId: 'mindmate-app-fcf2d',
    storageBucket: 'mindmate-app-fcf2d.firebasestorage.app',
    iosBundleId: 'com.example.mindmate',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDipe8wc9MZ6TDn5Y5pe5_XUjbi1ExoC-c',
    appId: '1:279427655646:android:1effec0047a5ef7cf3df4f',
    messagingSenderId: '279427655646',
    projectId: 'mindmate-app-fcf2d',
    storageBucket: 'mindmate-app-fcf2d.firebasestorage.app',
  );
}
